# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: build-app-karsajobs-ui

on:
  push:
    branches: [ "karsajobs-ui" ]
  pull_request:
    branches: [ "karsajobs-ui" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build & Push Image
      run: |
        echo "${{ secrets.PASSPACKAGE }}" | docker login ghcr.io -u farahazhari --password-stdin
        docker build -t ghcr.io/farahazhari/ci-karsajobs-ui:latest .
        docker push ghcr.io/farahazhari/ci-karsajobs-ui:latest
