# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: test-app

on:
  push:
    branches: [ "karsajobs" ]
  pull_request:
    branches: [ "karsajobs" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
        
    - name: Test
      run: go test -v -short --count=1 $(go list ./...)
